# Generated by Django 4.1.6 on 2023-08-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='images/def.jpg', null=True, upload_to='images/'),
        ),
    ]
